name: Build and Upload Artifacts
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Set up JDK 8
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 8

      - name: Give permissions to Gradle
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Get repository name
        id: repo_name
        run: echo "::set-output name=name::$(basename -s .git ${{ github.repository }})"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ steps.repo_name.outputs.name }}
          path: build/libs/**.jar